### ISSUE TITLE
Trap signal when cputime limit exceeded

### ISSUE THREAD

**Issue by n-nishizawa** [djberg96/win32-process#18]
Thanks for your awesome gem, I can set cpu time limit by `Process.setrlimit(Process::RLIMIT_CPU, current_limit)` on windows 7.

But `Kernel.#trap` can't trap signal when cpu time exceeds the limit.
Is there any way to trap signal like `:XCPU` ?

**Comment by djberg96** [comment]
I don't think there's a way to trap it currently. To receive signals we would have to associate a completion port with the job, and that port would then receive notifications. I don't know if we could tie this back into Kernel.trap, but it's worth investigating.

**Comment by n-nishizawa** [comment]
Thanks for you quick reply!!
So I'd be happy, if I can trap the signal on windows.

In more detail, I'm trying to control cpu usage of ruby process a way based on [this code](http://blog.rubybestpractices.com/posts/ewong/017-Handling-excessive-CPU-Usage-within-a-Process.html).

Do you have any other idea to handle cpu usage of ruby process?
